set_property PACKAGE_PIN P8 [get_ports {io_sel[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[0]}]
set_property PACKAGE_PIN R8 [get_ports {io_sel[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[1]}]
set_property PACKAGE_PIN N9 [get_ports {io_sel[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[2]}]
set_property PACKAGE_PIN P9 [get_ports {io_sel[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[3]}]
    
set_property PACKAGE_PIN T5 [get_ports {io_seg[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[0]}]
set_property PACKAGE_PIN R5 [get_ports {io_seg[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[1]}]
set_property PACKAGE_PIN T9 [get_ports {io_seg[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[2]}]
set_property PACKAGE_PIN R6 [get_ports {io_seg[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[3]}]
set_property PACKAGE_PIN R7 [get_ports {io_seg[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[4]}]
set_property PACKAGE_PIN T7 [get_ports {io_seg[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[5]}]
set_property PACKAGE_PIN T8 [get_ports {io_seg[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[6]}]

set_property PACKAGE_PIN C6 [get_ports {up}]
    set_property IOSTANDARD LVCMOS33 [get_ports {up}]
    set_property PULLDOWN true [get_ports {up}]

set_property PACKAGE_PIN P11 [get_ports {clear}]
    set_property IOSTANDARD LVCMOS33 [get_ports {clear}]
    set_property PULLDOWN true [get_ports {clear}]

set_property PACKAGE_PIN A7 [get_ports {dw}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dw}]
    set_property PULLDOWN true [get_ports {dw}]
