webtalk_init -webtalk_dir C:/Users/adityasehgal/Documents/GitHub/Verilog_Projects/Basic_Btn_Counter/Basic_Btn_Counter.sim/sim_1/behav/xsim/xsim.dir/clk_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 25 23:07:15 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2580384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ad85b3b8-fe4d-477a-8757-6cc2e4756bd6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb481af07b4d426bb5960ea424f1ba73" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12538922 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "22.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14052_KB" -context "xsim\\usage"
webtalk_transmit -clientid 743516361 -regid "" -xml C:/Users/adityasehgal/Documents/GitHub/Verilog_Projects/Basic_Btn_Counter/Basic_Btn_Counter.sim/sim_1/behav/xsim/xsim.dir/clk_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/adityasehgal/Documents/GitHub/Verilog_Projects/Basic_Btn_Counter/Basic_Btn_Counter.sim/sim_1/behav/xsim/xsim.dir/clk_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/adityasehgal/Documents/GitHub/Verilog_Projects/Basic_Btn_Counter/Basic_Btn_Counter.sim/sim_1/behav/xsim/xsim.dir/clk_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
